name: "Update"
description: Updates the BiomeJS version & hashes

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - updater/*
      - updater/**/*

jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - run: |
          pacman -Syu --noconfirm base-devel git

      - uses: actions/checkout@v6

      - name: Setup Rust and Cargo
        uses: moonrepo/setup-rust@v1
        with:
          target-dirs: "updater/target"

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Run updater
        run: cd updater && cargo run

      - name: Update .SRCINFO file
        run: EUID=1 makepkg --printsrcinfo > .SRCINFO

      - name: Commit PKGBUILD updates
        run: |
          git add PKGBUILD .SRCINFO
          git commit -m 'deps: bump BiomeJS version' || exit 0
          git push"
