name: "Update"
description: Updates the BiomeJS version & hashes

on:
    schedule:
        - cron: "*/5 * * * *"
    workflow_dispatch:
    workflow_call:
    push:
        paths:
            - updater/

jobs:
    update:
        runs-on: ubuntu-slim
        steps:
            - uses: actions/checkout@v6
            - name: Setup Rust and Cargo
              uses: moonrepo/setup-rust@v1.2.2

            - name: Setup Git
              run: |
                git config --global user.name "GitHub Actions"
                git config --global user.email "actions@github.com"

            - run: cd updater

            - run: cargo run
            - run: "git commit -a 'deps: bump BiomeJS version' && git push"
