name: "Update"
description: Updates the BiomeJS version & hashes

on:
    schedule:
        - cron: "*/5 * * * *"
    workflow_dispatch:
    workflow_call:
    push:
        paths:
            - updater/

jobs:
    update:
        runs-on: ubuntu-slim
        steps:
            - uses: actions/checkout@v6
            - name: Setup Rust and Cargo
              uses: moonrepo/setup-rust@v1.2.2

            - name: Setup Git
              run: |
                git config --global user.name "GitHub Actions"
                git config --global user.email "actions@github.com"

            - run: cd updater && cargo run

            - name: Commit PKGBUILD updates
              run: |
                git add PKGBUILD
                git commit -m 'deps: bump BiomeJS version' || exit 0
                git push"
